name: Run JPA test

on: [push]

jobs:
  jpa-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test JPA assignment
        run: mvn --batch-mode --update-snapshots verify
        working-directory: Assignments/AssignmentB
